import React, { useState } from 'react';
import './App.css';

const LANGUAGES = ['Python', 'JavaScript', 'TypeScript', 'Java', 'Go', 'SQL'];

function DocCard({ title, content }) {
  const [expanded, setExpanded] = useState(false);
  return (
    <div className="doc-card">
      <div className="doc-card-header">
        <div className="doc-dot"></div>
        <div className="doc-card-title">{title.toUpperCase()}</div>
      </div>
      <div className={`doc-card-body ${expanded ? 'expanded' : ''}`}>
        {content}
      </div>
      <button className="expand-btn" onClick={() => setExpanded(!expanded)}>
        {expanded ? '▲ Show Less' : '▼ Show More'}
      </button>
    </div>
  );
}

function App() {
  const [code, setCode] = useState('');
  const [lang, setLang] = useState('Python');
  const [docs, setDocs] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const generateDocs = async () => {
    if (!code.trim()) { alert('Please paste some code first!'); return; }
    if (code.length > 3000) {
      setError('⚠️ Code is too long. Please paste a smaller snippet (under 3000 characters) for best results.');
      return;
    }
    setLoading(true);
    setError('');
    setDocs([]);

    const prompt = `<s>[INST] You are a technical documentation expert. Analyze this ${lang} code and return ONLY a JSON array with exactly 5 objects. No extra text, no markdown, no backticks.

CODE:
${code}

Return exactly this format:
[
  {"title": "Overview", "content": "Explain what this code does in 3-4 sentences"},
  {"title": "Functions & Methods", "content": "List every function with its name and what it does"},
  {"title": "Parameters & Returns", "content": "For each function list parameters, types, and return values"},
  {"title": "Usage Examples", "content": "Show 2-3 practical examples of how to use this code"},
  {"title": "Edge Cases & Errors", "content": "List potential errors and edge cases"}
] [/INST]`;

    try {
      const response = await fetch(
        'https://api-inference.huggingface.co/models/mistralai/Mistral-7B-Instruct-v0.2',
        {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': `Bearer ${process.env.REACT_APP_HF_KEY}`
          },
          body: JSON.stringify({
            inputs: prompt,
            parameters: {
              max_new_tokens: 1500,
              temperature: 0.1,
              return_full_text: false
            }
          })
        }
      );

      const data = await response.json();

      if (!data || !data[0] || !data[0].generated_text) {
        throw new Error('Could not generate documentation. Please try again.');
      }

      const text = data[0].generated_text;
      const match = text.match(/\[[\s\S]*\]/);
      if (!match) throw new Error('Could not parse response. Please try again.');
      const sections = JSON.parse(match[0]);
      setDocs(sections);

    } catch (err) {
      setError('⚠️ ' + err.message);
    }

    setLoading(false);
  };

  const copyDocs = () => {
    const md = docs.map(d => `## ${d.title}\n\n${d.content}`).join('\n\n---\n\n');
    navigator.clipboard.writeText(md);
    alert('Copied to clipboard!');
  };

  const downloadDocs = () => {
    const md = `# Documentation\nGenerated by DocuMind AI\n\n---\n\n` +
      docs.map(d => `## ${d.title}\n\n${d.content}`).join('\n\n---\n\n');
    const blob = new Blob([md], { type: 'text/markdown' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = 'documentation.md';
    a.click();
  };

  return (
    <div>
      <div className="header">
        <div>
          <div className="logo">DocuMind AI</div>
          <div className="tagline">Technical Documentation Generator</div>
        </div>
      </div>

      <div className="main">
        <div className="left-panel">
          <div>
            <div className="label">Language</div>
            <div className="lang-tabs">
              {LANGUAGES.map(l => (
                <button
                  key={l}
                  className={`lang-tab ${lang === l ? 'active' : ''}`}
                  onClick={() => setLang(l)}
                >
                  {l}
                </button>
              ))}
            </div>
          </div>

          <div style={{ flex: 1, display: 'flex', flexDirection: 'column' }}>
            <div className="label">Paste your code</div>
            <textarea
              className="code-input"
              value={code}
              onChange={e => setCode(e.target.value)}
              placeholder="Paste your functions, classes, or APIs here..."
            />
          </div>

          <button className="generate-btn" onClick={generateDocs} disabled={loading}>
            {loading
              ? <><span className="spinner"></span>GENERATING...</>
              : 'GENERATE DOCUMENTATION →'}
          </button>
        </div>

        <div className="right-panel">
          <div className="label">Generated Documentation</div>

          {!loading && docs.length === 0 && !error && (
            <div className="empty-state">
              <div className="empty-icon">📄</div>
              <div className="empty-title">No docs yet</div>
              <div className="empty-sub">Paste your code and click Generate</div>
            </div>
          )}

          {error && <div className="error">{error}</div>}

          {docs.map((doc, i) => (
            <DocCard key={i} title={doc.title} content={doc.content} />
          ))}

          {docs.length > 0 && (
            <div className="action-btns">
              <button className="action-btn" onClick={copyDocs}>📋 Copy Markdown</button>
              <button className="action-btn" onClick={downloadDocs}>⬇ Download .md</button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

export default App;