import React, { useState } from 'react';
import './App.css';

const LANGUAGES = ['Python', 'JavaScript', 'TypeScript', 'Java', 'Go', 'SQL'];

function App() {
  const [code, setCode] = useState('');
  const [lang, setLang] = useState('Python');
  const [docs, setDocs] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const generateDocs = async () => {
    if (!code.trim()) { alert('Please paste some code first!'); return; }
    setLoading(true);
    setError('');
    setDocs([]);

    try {
      const response = await fetch('https://openrouter.ai/api/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${process.env.REACT_APP_OPENROUTER_KEY}`
        },
        body: JSON.stringify({
          model: 'google/gemini-flash-1.5',
          messages: [{
            role: 'user',
            content: `You are a technical documentation expert. Analyze this ${lang} code and generate clear documentation.

CODE:
${code}

Return a JSON array only (no extra text) with objects having "title" and "content":
[{"title": "Overview", "content": "..."},
 {"title": "Functions & Methods", "content": "..."},
 {"title": "Parameters & Returns", "content": "..."},
 {"title": "Usage Examples", "content": "..."},
 {"title": "Edge Cases", "content": "..."}]`
          }]
        })
      });

      const data = await response.json();
      const text = data.choices[0].message.content;
      const cleaned = text.replace(/```json|```/g, '').trim();
      const sections = JSON.parse(cleaned);
      setDocs(sections);
    } catch (err) {
      setError('Something went wrong. Check your API key in .env file.');
    }

    setLoading(false);
  };

  const copyDocs = () => {
    const md = docs.map(d => `## ${d.title}\n\n${d.content}`).join('\n\n---\n\n');
    navigator.clipboard.writeText(md);
    alert('Copied to clipboard!');
  };

  const downloadDocs = () => {
    const md = `# Documentation\nGenerated by DocuMind AI\n\n---\n\n` +
      docs.map(d => `## ${d.title}\n\n${d.content}`).join('\n\n---\n\n');
    const blob = new Blob([md], { type: 'text/markdown' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = 'documentation.md';
    a.click();
  };

  return (
    <div>
      <div className="header">
        <div>
          <div className="logo">DocuMind AI</div>
          <div className="tagline">Technical Documentation Generator</div>
        </div>
      </div>

      <div className="main">
        <div className="left-panel">
          <div>
            <div className="label">Language</div>
            <div className="lang-tabs">
              {LANGUAGES.map(l => (
                <button key={l} className={`lang-tab ${lang === l ? 'active' : ''}`}
                  onClick={() => setLang(l)}>{l}</button>
              ))}
            </div>
          </div>

          <div style={{flex: 1, display: 'flex', flexDirection: 'column'}}>
            <div className="label">Paste your code</div>
            <textarea className="code-input" value={code}
              onChange={e => setCode(e.target.value)}
              placeholder="Paste your functions, classes, or APIs here..." />
          </div>

          <button className="generate-btn" onClick={generateDocs} disabled={loading}>
            {loading ? <><span className="spinner"></span>GENERATING...</> : 'GENERATE DOCUMENTATION →'}
          </button>
        </div>

        <div className="right-panel">
          <div className="label">Generated Documentation</div>

          {!loading && docs.length === 0 && !error && (
            <div className="empty-state">
              <div className="empty-icon">📄</div>
              <div className="empty-title">No docs yet</div>
              <div className="empty-sub">Paste your code and click Generate</div>
            </div>
          )}

          {error && <div className="error">{error}</div>}

          {docs.map((doc, i) => (
            <div className="doc-card" key={i}>
              <div className="doc-card-header">
                <div className="doc-dot"></div>
                <div className="doc-card-title">{doc.title.toUpperCase()}</div>
              </div>
              <div className="doc-card-body">{doc.content}</div>
            </div>
          ))}

          {docs.length > 0 && (
            <div className="action-btns">
              <button className="action-btn" onClick={copyDocs}>📋 Copy Markdown</button>
              <button className="action-btn" onClick={downloadDocs}>⬇ Download .md</button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

export default App;