import React, { useState } from 'react';
import './App.css';

const LANGUAGES = ['Python', 'JavaScript', 'TypeScript', 'Java', 'Go', 'SQL'];

function DocCard({ title, content }) {
  const [expanded, setExpanded] = useState(false);

  return (
    <div className="doc-card">
      <div className="doc-card-header">
        <div className="doc-dot"></div>
        <div className="doc-card-title">{title.toUpperCase()}</div>
      </div>
      <div className={`doc-card-body ${expanded ? 'expanded' : ''}`}>
        {content}
      </div>
      <button className="expand-btn" onClick={() => setExpanded(!expanded)}>
        {expanded ? '▲ Show Less' : '▼ Show More'}
      </button>
    </div>
  );
}

function App() {
  const [code, setCode] = useState('');
  const [lang, setLang] = useState('Python');
  const [docs, setDocs] = useState([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState('');

  const generateDocs = async () => {
    if (!code.trim()) { alert('Please paste some code first!'); return; }
    setLoading(true);
    setError('');
    setDocs([]);

    try {
      const prompt = `You are a technical documentation expert. Analyze this ${lang} code carefully and generate comprehensive documentation.

CODE:
${code}

Return ONLY a JSON array with exactly these 5 objects, no extra text:
[
  {"title": "Overview", "content": "Explain what this code does, its purpose and main functionality in 3-4 sentences"},
  {"title": "Functions & Methods", "content": "List every function/method with its name and what it does"},
  {"title": "Parameters & Returns", "content": "For each function list its parameters, their types, and what it returns"},
  {"title": "Usage Examples", "content": "Show 2-3 real practical examples of how to use this code"},
  {"title": "Edge Cases & Errors", "content": "List potential errors, edge cases and how to handle them"}
]`;

      const response = await fetch('https://api.groq.com/openai/v1/chat/completions', {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': `Bearer ${process.env.REACT_APP_GROQ_KEY}`
        },
        body: JSON.stringify({
          model: 'llama-3.1-8b-instant',
          messages: [
            {
              role: 'system',
              content: 'You are a documentation expert. Always respond with valid JSON array only. No markdown. No extra text.'
            },
            {
              role: 'user',
              content: prompt
            }
          ],
          temperature: 0.1,
          max_tokens: 2048
        })
      });

      const data = await response.json();
      const text = data.choices[0].message.content;
      const match = text.match(/\[[\s\S]*\]/);
      if (!match) throw new Error('No valid JSON in response');
      const sections = JSON.parse(match[0]);
      setDocs(sections);

    } catch (err) {
      setError('Something went wrong: ' + err.message);
    }

    setLoading(false);
  };

  const copyDocs = () => {
    const md = docs.map(d => `## ${d.title}\n\n${d.content}`).join('\n\n---\n\n');
    navigator.clipboard.writeText(md);
    alert('Copied to clipboard!');
  };

  const downloadDocs = () => {
    const md = `# Documentation\nGenerated by DocuMind AI\n\n---\n\n` +
      docs.map(d => `## ${d.title}\n\n${d.content}`).join('\n\n---\n\n');
    const blob = new Blob([md], { type: 'text/markdown' });
    const a = document.createElement('a');
    a.href = URL.createObjectURL(blob);
    a.download = 'documentation.md';
    a.click();
  };

  return (
    <div>
      <div className="header">
        <div>
          <div className="logo">DocuMind AI</div>
          <div className="tagline">Technical Documentation Generator</div>
        </div>
      </div>

      <div className="main">
        <div className="left-panel">
          <div>
            <div className="label">Language</div>
            <div className="lang-tabs">
              {LANGUAGES.map(l => (
                <button
                  key={l}
                  className={`lang-tab ${lang === l ? 'active' : ''}`}
                  onClick={() => setLang(l)}
                >
                  {l}
                </button>
              ))}
            </div>
          </div>

          <div style={{ flex: 1, display: 'flex', flexDirection: 'column' }}>
            <div className="label">Paste your code</div>
            <textarea
              className="code-input"
              value={code}
              onChange={e => setCode(e.target.value)}
              placeholder="Paste your functions, classes, or APIs here..."
            />
          </div>

          <button className="generate-btn" onClick={generateDocs} disabled={loading}>
            {loading
              ? <><span className="spinner"></span>GENERATING...</>
              : 'GENERATE DOCUMENTATION →'}
          </button>
        </div>

        <div className="right-panel">
          <div className="label">Generated Documentation</div>

          {!loading && docs.length === 0 && !error && (
            <div className="empty-state">
              <div className="empty-icon">📄</div>
              <div className="empty-title">No docs yet</div>
              <div className="empty-sub">Paste your code and click Generate</div>
            </div>
          )}

          {error && <div className="error">{error}</div>}

          {docs.map((doc, i) => (
            <DocCard key={i} title={doc.title} content={doc.content} />
          ))}

          {docs.length > 0 && (
            <div className="action-btns">
              <button className="action-btn" onClick={copyDocs}>📋 Copy Markdown</button>
              <button className="action-btn" onClick={downloadDocs}>⬇ Download .md</button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
}

export default App;